# -*- coding: utf-8 -*-
"""EDA For Students .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQ2GWRHckU1v1EqyLkeaXfUteNTnIHeN
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("/content/sample_data/StudentPerformanceFactors.csv")

# Display first 5 rows
print(df.head(5))

# Dataset info
print(df.info())

# Fill missing values with mode
df['Teacher_Quality'].fillna(df['Teacher_Quality'].mode()[0], inplace=True)
df['Parental_Education_Level'].fillna(df['Parental_Education_Level'].mode()[0], inplace=True)
df['Distance_from_Home'].fillna(df['Distance_from_Home'].mode()[0], inplace=True)

# Remove duplicate rows
df = df.drop_duplicates()

# Select relevant columns
A_Plus = df[["Hours_Studied", "Exam_Score", "Previous_Scores", "Parental_Involvement", "Internet_Access"]]

# Correct grade filtering
A_Grade = A_Plus[A_Plus["Exam_Score"] >= 90]
B_Grade = A_Plus[(A_Plus["Exam_Score"] >= 80) & (A_Plus["Exam_Score"] < 90)]
C_Grade = A_Plus[(A_Plus["Exam_Score"] >= 70) & (A_Plus["Exam_Score"] < 80)]

# Histogram for A Grade students' exam scores
A_Grade["Exam_Score"].hist(bins=10, color="skyblue")
plt.title("Distribution of Exam Scores for A Grade Students")
plt.xlabel("Exam Score")
plt.ylabel("Frequency")
plt.show()

# Scatter plot: Hours Studied vs Exam Score (A Grade)
sns.scatterplot(x=A_Grade["Hours_Studied"], y=A_Grade["Exam_Score"])
plt.title("A Grade Students Study Hours vs Exam Score")
plt.show()

# Scatter plot: Previous Scores vs Exam Score (A Grade)
sns.scatterplot(x=A_Grade["Previous_Scores"], y=A_Grade["Exam_Score"])
plt.title("A Grade Student Previous Marks vs Exam Score")
plt.show()

# Box plot: Parental Involvement vs Exam Score (A Grade)
sns.boxplot(x=A_Grade["Parental_Involvement"].astype(str), y=A_Grade["Exam_Score"])
plt.title("Parental Involvement vs Exam Score")
plt.show()